defmodule MyAppWeb.Components.Hero do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  import MyAppWeb.Gettext

  @doc "The name"
  prop name, :string, default: "Guest"

  @doc "The subtitle"
  prop subtitle, :string

  @doc "The color"
  prop color, :string, values!: ["danger", "info", "warning", "primary"], default: "info"

  @doc "Additional classes set by parent."
  prop class, :string

  def render(assigns) do
    ~F"""
    <section class={"hero", "is-#{@color}", @class}>
      <div class="hero-body">
        <p class="title">
          {gettext("Hi, %{name}!", name: @name)}
        </p>
        <p class="subtitle">
          {@subtitle}
        </p>
      </div>
    </section>
    """
  end
end
